# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=20, verbose_name='\u5e74\u9f84'),
        ),
    ]
